version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: convertax-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: convertax
      POSTGRES_USER: glaymar2010@gmail.com
      POSTGRES_PASSWORD: nada
      
  redis:
    image: redis:latest
    container_name: convertax-redis
    ports:
      - "6379:6379"
